### PR TITLE
Update to latest Pods and fixed crashes from forced unwraps

### PR DESCRIPTION
**Pull request by imaczealot**
Update Pods
Fix crashes
Swift code clean up
Add print statements useful for learning the project
Recommend not tracking (including in git) all files from Pods directory

### CODE REVIEW

**Comment by imaczealot** [comment]
I ran into many crashes evaluating the code.  I fixed several and did some code clean up.

I'd recommend removing some of the files that are being tracked.  I've added a standard .gitignore file to help, but all existing tracked files will need to be removed from git cache.

**Comment by sf-jed-kyung** [comment]
@imaczealot  Thank you for your interest. We are preparing the new version of this project. The new project will have a new UI, new structures, and more features. That's why I'm not able to merge your PR now. But, I'll adopt many things from your PR and apply them to the new version. They will be very helpful for the new one and I hope we can release it soon. Thanks again for your interest in this project.

**Comment by imaczealot** [comment]
That's great!  Can you give a timeframe for when the next release will be posted?

**Comment by ezet** [comment]
We are also interested in a timeframe for the updated version?

**Pull request closed without merging**
